"""Alembic async environment configuration.

NOTE: The partial unique index `idx_sprints_one_active_per_project` on
sprints(project_id) WHERE status = 'active' is defined in the Sprint model's
__table_args__ and should be picked up by autogenerate. However, always verify
that autogenerated migrations include it correctly. If not, add it manually:

    op.create_index(
        'idx_sprints_one_active_per_project',
        'sprints',
        ['project_id'],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
"""
import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

from app.core.config import settings
from app.models import Base  # noqa: F401 — ensures all models are imported

config = context.config
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Detect column type changes during autogenerate (e.g. String(255) →
        # String(512)).  Without this flag Alembic silently ignores type diffs.
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
